version: '3.1'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 5555:80
        volumes:
            - ./src:/var/www/html

    db:
        image: 'mariadb:10.6.4'
        restart: always
        env_file:
            - .env
        volumes:
            - ./dumpSql/data.sql:/docker-entrypoint-initdb.d/data.sql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8888:80
        environment:
            - PMA_ARBITRARY=1
